name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: amazon
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@main
    - name: Install Dependencies
      run: |
        pwd
        python -m pip install --upgrade pip
        pip install virtualenv
        python -m venv
        python -m pip install django
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py migrate
    - name: Deploy
      run: | 
        screen -d -t python manage.py runserver 0.0.0.0:8000
