name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: amazon
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@main
    - name: Stop running processes
      run: |
        kill -9 $(pidof python3 manage.py runserver 0.0.0.0:8000)
    - name: Install Dependencies
      working-directory: ./djangoprjt
      run: |
        pwd
        python3 -m pip install --upgrade pip
        pip install virtualenv
        virtualenv djangoprjt/
        python3 -m pip install django
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: ./djangoprjt
      run: |
        pwd 
        python3 manage.py migrate
    - name: Deploy
      working-directory: ./djangoprjt
      run: | 
        screen -d -m python3 manage.py runserver 0.0.0.0:8000
