name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: amazon
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@main
    - name: Install Dependencies
      run: |
        pwd
        python3 -m pip install --upgrade pip
        pip install virtualenv
        virtualenv djangoprjt/
        python3 -m pip install django
        pwd
        cd djangoprjt
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        pwd 
        cd djangoprjt
        python3 manage.py migrate
    - name: Deploy
      run: | 
        screen -d -m python3 djangoprit/manage.py runserver 0.0.0.0:8000
